FROM node:16.13.0-bullseye

EXPOSE 9099
EXPOSE 8080

USER root
RUN apt-get update \
    && apt-get install -y default-jre \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER node
WORKDIR /home/node/app

CMD ["npm", "run", "emulate"]
